### ISSUE TITLE
exec /bin/opm: exec format error

### ISSUE THREAD

**Issue by jianzhangbjz** [Xia-Zhao-rh/multi-arch-operators#1]
I followed this https://github.com/Xia-Zhao-rh/multi-arch-operators/blob/master/nginx-operator-24644/steps/steps.txt, but got the below errors:
```yaml
mac:openshift-tests-private jianzhang$ oc get pods
NAME                                                              READY   STATUS             RESTARTS      AGE
11fd0eac78dbaedde537bb34420d7329334ff5027cfe8f2ff44410f6a7m57p4   0/1     Completed          0             7h39m
4fedc4ee8a6e985565ad7797d3eb2667b600e5331af4293f69fa73b2f2c9x8t   0/1     Completed          0             7h39m
certified-operators-thxbq                                         1/1     Running            0             8h
community-operators-hj7cl                                         1/1     Running            0             8h
marketplace-operator-f6dcbb88d-njttt                              1/1     Running            0             8h
multi-operator-8psm5                                              0/1     CrashLoopBackOff   1 (15s ago)   20s
qe-app-registry-fcslw                                             1/1     Running            0             35m
redhat-marketplace-kqwpt                                          1/1     Running            0             8h
redhat-operators-hvbkc                                            1/1     Running            0             4m
mac:openshift-tests-private jianzhang$ oc logs multi-operator-8psm5  
exec /bin/opm: exec format error
mac:openshift-tests-private jianzhang$ oc get clusterversion
NAME      VERSION                                    AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.10.0-0.nightly-arm64-2022-04-17-065208   True        False         7h57m   Cluster version is 4.10.0-0.nightly-arm64-2022-04-17-065208
```
The CatalogSource file:
```yaml
mac:openshift-tests-private jianzhang$ cat ~/cs-multi.yaml 
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: multi-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/olmqe/learn-operator-index:v1
  displayName: Sample Operators
  publisher: Jian
```
